"""Add session_id to CartItem

Revision ID: f5cc3e9e52ca
Revises: b8d7614e2cbc
Create Date: 2024-10-19 00:26:08.144326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5cc3e9e52ca'
down_revision = 'b8d7614e2cbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
